### PR TITLE
Add Deno.fsEvents

### PR DESCRIPTION
**Pull request by Nautigsam**
In next version, `Deno.fsEvents()` function will be added. This removes the need for deno-watch and deno-watch-v2 repositories.

To try it, you must compile deno on master branch.

If needed I will update it when version v0.35.0 is out. In the meantime you can see that it works fine. There are still some errors in tests, I did not try to fix them.

### CODE REVIEW

**Comment by ebebbington** [comment]
Nice work! I’ll look into it this weekend.

**Comment by ebebbington** [comment]
Where/how did you manage to get v0.35.0?

**Comment by Nautigsam** [comment]
I built Deno from the sources.

**Comment by ebebbington** [comment]
How did you go about it? Eg link or docs on how to as I haven’t managed to figure out it myself

**Comment by Nautigsam** [comment]
I followed [these instructions](https://deno.land/std/manual.md#development). But v0.35.0 just got released so you may not need it for now :slightly_smiling_face:

**Comment by ebebbington** [comment]
Nice work, greatly appreciated :) Also means the maintenance is reduced by pretty much half

**Pull request merged**
